version: '3.8'

services:
  jekyll-site:
    image: jekyll-site
    build: .
    volumes:
      - /Users/audreyyuan/Downloads/personalweb-master:/usr/src/app
    ports:
      - "4000:4000"
    user: 1000:1000
    environment:
      JEKYLL_ENV: docker